---
kind: pipeline
type: docker
name: Rankade.py – Dev publish

steps:
  - name: dev_publish
    image: plugins/pypi
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      repository:
        https://git.14zombies.com/api/packages/cal/pypi

trigger:
  event:
    - push
---
kind: pipeline
type: docker
name: Rankade.py – PYPI publish

steps:
  - name: pypi_publish
    image: plugins/pypi
    settings:
      username: __token__
      password:
        from_secret: pypi_token
trigger:
  event:
    - tag
---
####
#
# BUILD AMD64 IMAGE
#
####
kind: pipeline
type: docker
name: build linux-amd64 (Docs)
platform:
  os: linux
  arch: amd64

steps:
  - name: Docker image build & push (linux-amd64)
    image: plugins/docker
    settings:
      dockerfile: docs/docker/Dockerfile
      registry: git.14zombies.com
      username:
        from_secret: username
      password:
        from_secret: password
      repo: git.14zombies.com/cal/rankade.py
      auto_tag: true
      auto_tag_suffix: linux-amd64
      platforms:
        - linux/amd64
trigger:
  event:
    - tag
    - push


---
####
#
# BUILD ARM64 IMAGE
#
####
kind: pipeline
type: docker
name: build linux-arm64 (Docs)
platform:
  os: linux
  arch: arm64

steps:
  - name: Docker image build & push (linux-arm64)
    image: plugins/docker
    settings:
      dockerfile: docs/docker/Dockerfile
      registry: git.14zombies.com
      username:
        from_secret: username
      password:
        from_secret: password
      repo: git.14zombies.com/cal/rankade.py
      auto_tag: true
      auto_tag_suffix: linux-arm64
      platforms:
        - linux/arm64
trigger:
  event:
    - tag
    - push


---
####
#
# BUILD MANIFEST
#
####
kind: pipeline
type: docker
name: manifest (Docs)
steps:
  - name: manifest
    image: plugins/manifest
    settings:
      spec: docs/docker/manifest.tmpl
      ignore_missing: true
      registry: git.14zombies.com
      password:
        from_secret: password
      username:
        from_secret: username
depends_on:
  - build linux-amd64 (Docs)
  - build linux-arm64 (Docs)


---
####
#
# DEPLOY TAGGED IMAGE
#
####
kind: pipeline
type: docker
name: Deploy (Docs)
clone:
  disable: true
steps:
  - name: deploy – webhook
    image: plugins/webhook
    settings:
      urls:
        from_secret: hook
depends_on:
  - build linux-amd64 (Docs)
  - build linux-arm64 (Docs)
trigger:
  event:
    - tag
    - push


---
kind: signature
hmac: 05cea88b2d974ca249c8854d85cc4f829ff7d52bc3c0743da9e6be3ef57b4625

...
