name: Build Package 📦
on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        # uses: actions/upload-artifact@v4
        # To be changed back to actions/upload-artifact@v4 when Github supports v4 artifacts, it's hard coded.
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/') # only publish to PyPI on tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/rankade.py/ # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download all the dists
        # uses: actions/download-artifact@v4
        # To be changed back to actions/upload-artifact@v4 when Github supports v4 artifacts, it's hard coded.
        uses: christopherhx/gitea-download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Can be removed once gitea adds GITHUB_WORKFLOW_REF TO Actions.
        env:
          GITHUB_WORKFLOW_REF: testing
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/rankade.py/

    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        # uses: actions/download-artifact@v4
        # To be changed back to actions/upload-artifact@v4 when Github supports v4 artifacts, it's hard coded.
        uses: christopherhx/gitea-download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Can be removed once gitea adds GITHUB_WORKFLOW_REF TO Actions.
        env:
          GITHUB_WORKFLOW_REF: testing
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
