"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import ClassVar, Type

from rankade.api.Api import JSON

from .Base import RankadeObject, ResultList
from .Player import Players

@dataclass(kw_only=True, slots=True)
class Faction(RankadeObject):
    """Represents a faction used within a Match."""
    name: str
    points: str
    rank: int
    bot: bool = ...
    winner: bool = ...
    players: Players
    countPlayers: int = ...
    def __post_init__(self) -> None:
        ...

    @property
    def is_bot(self) -> bool:
        """Convenience attribute - returns true if faction is bot faction."""
        ...

    @property
    def is_winner(self) -> bool:
        """Convenience attribute - returns true if faction is winning faction."""
        ...

    def as_dict(self) -> JSON:
        """
        Returns a custom dictionary for new match server post request.
        """
        ...



@dataclass(kw_only=True, slots=True)
class Factions(ResultList[Faction]):
    """
    Represents a list of faction objects returned by the Rankade server.
    Individual faction objects returned by the server can be accessed in the same way as a regular list.
    """
    _content_class: ClassVar[Type[RankadeObject]] = ...


