"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import ClassVar, Optional, Type

from rankade.api.Api import JSON

from .Base import RankadeObject, ResultList
from .Faction import Factions
from .Game import Game
from .Player import Player, Players

"""
This type stub file was generated by pyright.
"""
@dataclass
class NewMatch(RankadeObject):
    """This class to be used for creating Matches to post to the Rankade API."""
    notes: str
    name: str = ...
    game: Optional[Game] = ...
    factions: Optional[Factions] = ...
    weight: str = ...
    def add_bot_faction(self, rank: int, points: str, name: str = ...) -> None:
        """
        Convenience method to add a bot faction to the match.
        """
        ...

    def add_faction(self, players: Players, rank: int, points: str, name: str = ..., bot: bool = ...) -> None:
        """
        Convenience method to add a faction to the match.
        """
        ...

    def add_single_player_faction(self, player: Player, rank: int, points: str, name: str = ..., bot: bool = ...) -> None:
        """
        Convenience method to add a faction to the match, with just one player.
        """
        ...

    def as_dict(self) -> JSON:
        """
        Returns a custom dictionary for new match server post request.
        """
        ...



@dataclass
class NewMatchList(ResultList[NewMatch]):
    """
    Represents the list of NewMatches returned by the Rankade server.
    Individual NewMatch objects returned by the server can be accessed in the same way as a regular list.
    """
    _content_class: ClassVar[Type[RankadeObject]] = ...


