"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

from .Base import RankadeObject

@dataclass(kw_only=True, slots=True)
class Quota(RankadeObject):
    """
    Rankade Quota usage. All items returned as a percentage of total used.
    :::{seealso}
    Quota limits depend on the subscription tier full list can be found on the [Quota and limits](https://rankade.com/api/#quota-and-limits) section of the Rankade API page.
    """
    callsPerYear: str
    callsPerHour: str
    matchesPerYear: str
    matchesPerDay: str
    matchesPerHour: str
    rankingCallsPerYear: str
    rankingCallsPerDay: str
    rankingCallsPerHour: str
    apiCreatedGames: str
    ...


