"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import ClassVar, Optional, Type

from .Base import Page, RankadeObject, ResultList
from .Match import Match
from .Player import Player
from .Subset import Subset

@dataclass(kw_only=True)
class Ranking(RankadeObject):
    """Individual Ranking of a player in the subset."""

    ree: int
    deltaRee: int
    position: int
    deltaPosition: int
    belt: int
    beltLabel: str
    title: int
    titleLabel: str
    status: int
    statusLabel: str
    player: Player
    def __post_init__(self) -> None: ...

@dataclass(kw_only=True, slots=True)
class Rankings(ResultList[Ranking], Page):
    """
    Represents the list of Rankings returned by the Rankade server.
    Individual ranking objects returned by the server can be accessed in the same way as a regular list.
    """

    _content_class: ClassVar[Type[RankadeObject]] = ...
    match: Optional[Match]
    subset: Optional[Subset]
    def __post_init__(self) -> None: ...
    def sort_by_position(self) -> None:
        """Sort Rankings by position."""
        ...

    def sort_by_delta_position(self) -> None:
        """Sort Rankings by change of position."""
        ...

    def sort_by_ree(self) -> None:
        """Sort Rankings by Ree score."""
        ...

    def sort_by_delta_ree(self) -> None:
        """Sort Rankings by change of Ree score."""
        ...
