"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import ClassVar, Optional, Type

from .Base import RankadeObject, ResultList
from .Game import Game
from .Match import Match, Matches

"""
This type stub file was generated by pyright.
"""
@dataclass(kw_only=True, slots=True)
class Subset(RankadeObject):
    """Represents a groups subset."""
    id: str
    name: str
    type: str
    creationDate: datetime
    isMain: bool
    isCustom: bool
    icon: str
    countMatches: int
    game: Optional[Game]
    firstMatch: Match
    lastMatch: Match
    def __post_init__(self) -> None:
        ...

    @property
    def matches(self) -> Matches:
        """Includes bot the first and last match in the subset."""
        ...



@dataclass(kw_only=True, slots=True)
class Subsets(ResultList[Subset]):
    """
    Represents the list of subsets returned by the Rankade server.
    Individual subset objects returned by the server can be accessed in the same way as a regular list.
    """
    _content_class: ClassVar[Type[RankadeObject]] = ...


