"""
This type stub file was generated by pyright.
"""

import logging

from rankade import RankadeExceptions
from rankade.models import (
    Error,
    Errors,
    Faction,
    Factions,
    Game,
    Games,
    Match,
    Matches,
    MatchStatus,
    NewMatch,
    NewMatchList,
    NewMatchResponse,
    NewMatchReturn,
    NewMatchReturnList,
    Player,
    Players,
    Quota,
    RankadeObject,
    Ranking,
    Rankings,
    ResultList,
    Subset,
    Subsets,
)
from rankade.Rankade import Rankade

__title__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
__version__ = ...
__all__ = ["Rankade", "RankadeExceptions", "Error", "Errors", "Faction", "Factions", "Game", "Games", "Match", "Matches", "MatchStatus", "NewMatch", "NewMatchList", "NewMatchResponse", "NewMatchReturn", "NewMatchReturnList", "Player", "Players", "Quota", "RankadeObject", "Ranking", "Rankings", "ResultList", "Subset", "Subsets"]
