# Faction.py

from typing import Any, Dict

import rankade.Player
import rankade.RankadeObject


class Faction(rankade.RankadeObject.RankadeObject):

    def __eq__(self, other: rankade.RankadeObject.RankadeObject) -> bool: ...
    def __ne__(self, other: rankade.RankadeObject.RankadeObject) -> bool: ...
    def __lt__(self, other: rankade.RankadeObject.RankadeObject) -> bool: ...
    def __le__(self, other: rankade.RankadeObject.RankadeObject) -> bool: ...
    def __gt__(self, other: rankade.RankadeObject.RankadeObject) -> bool: ...
    def __ge__(self, other: rankade.RankadeObject.RankadeObject) -> bool: ...

    def _set_attributes(self, attributes: Dict[str, Any]) -> None: ...

    @property
    def is_bot(self) -> bool: ...

    def to_json(self) -> Dict[str, Any]: ...
