"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import ClassVar, Self, Type

from .Base import Page, RankadeObject, ResultList
from .Match import Match
from .Player import Player
from .Subset import Subset

@dataclass(kw_only=True)
class Ranking(RankadeObject):
    """Individual Ranking of a player in the subset."""
    ree: int
    deltaRee: int
    position: int
    deltaPosition: int
    belt: int
    beltLabel: str
    title: int
    titleLabel: str
    status: int
    statusLabel: str
    player: Player
    def __post_init__(self) -> None:
        ...



@dataclass(kw_only=True, slots=True)
class Rankings(ResultList[Ranking], Page):
    """
    Represents the list of Rankings returned by the Rankade server.
    Individual ranking objects returned by the server can be accessed in the same way as a regular list.
    """
    _content_class: ClassVar[Type[RankadeObject]] = ...
    match: Match
    subset: Subset
    def __post_init__(self) -> None:
        ...

    @property
    def sorted_by_position(self) -> Self:
        """Rankings sorted by position."""
        ...

    @property
    def sorted_by_delta_position(self) -> Self:
        """Rankings sorted by change of position."""
        ...

    @property
    def sorted_by_ree(self) -> Self:
        """Rankings sorted by Ree score."""
        ...

    @property
    def sorted_by_delta_ree(self) -> Self:
        """Rankings sorted by change of Ree score."""
        ...



